Add my blog
dgplug/studentsplanet pull request #21
Opened 2017-07-08 10:47 UTC by shankarj67

2017-07-21 03:06 UTC, kushaldas commented on planet.ini
> +name = Shankar Jha
Missing a newline.

2017-07-21 13:05 UTC, shankarj67 commented on planet.ini
> +name = Shankar Jha
where to add newline?

2017-11-06 17:32 UTC, kushaldas requested changes

2017-11-06 17:32 UTC, kushaldas commented on planet.ini
> +
Only 1 newline is required to mark the end of the file. It was explained the summer training.

2018-07-13 08:38 UTC, merged